### ISSUE TITLE
Suggest Topics for technical writing 

### ISSUE THREAD

**Issue by ankitmrmishra** [HACKTOBERFEST-2023-CHANDIGARH/blogging-hactoberfest-2023#1]
We are open to your suggestions
- We want some unique IDEAs for technical Blog Writing

**Comment by khushminder270** [comment]
Advantages of using GraphQL over RESTFUL APIs

**Comment by khushminder270** [comment]
Microservices Design Patterns

**Comment by ankitmrmishra** [comment]
@khushminder270 great topics. assigning you the `Advantages of using GraphQL over RESTFUL APIs`

**Comment by ankitmrmishra** [comment]
@khushminder270 and inviting you to create the PR in readme file and and add the topic `Microservices Design Patterns` .
If you can't, do let us know. We will add it by giving you credits

**Comment by Jatinsingal** [comment]
please assign this issue to me

**Comment by Jatinsingal** [comment]
employee handbooks, standard operating procedures (SOP), software user documentation (help files)

**Comment by khushminder270** [comment]
> @khushminder270 and inviting you to create the PR in readme file and and add the topic `Microservices Design Patterns` . If you can't, do let us know. We will add it by giving you credits

> @ankitmrmishra added topic Microservices Design Patterns in readme file

**Comment by khushminder270** [comment]
@ankitmrmishra 
Please add **Hacktoberfest-accepted** label
